name: Testing workflow

env:
  GITHUB_CONTEXT: ${ { toJson(github) } }
  COMMITS: ${ { toJson(github.event.commits) } }
  COMMIT_MESSAGES: ${ { toJson(github.event.commits.*.message) } }


on:
  push:
    branches:
      - pr-trigger-feature

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        run: echo "$GITHUB_CONTEXT"
      - name: github commits
        run: echo "$COMMITS"
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"
      #- name: skipping step if message has '#skip'
      #  run: echo "this shouldn't be printed if commit's message has '#skip' inside."

