name: Testing workflow

env:
  GITHUB_CONTEXT: ${{ toJSON(github) }}
  COMMITS: ${{ toJSON(github.event.commits) }}
  COMMIT_MESSAGES: ${{ toJSON(github.event.commits.*.message) }}
  JOINED_MESSAGES: ${{ join(${{ env.COMMIT_MESSAGES }}) }}
  SHOULD_SKIP_TAG_RELEASE: ${{ contains(${{ env.JOINED_MESSAGES }} , '#skip') }}


on:
  push:
    branches:
      - pr-trigger-feature

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        run: echo "$GITHUB_CONTEXT"
      - name: github commits
        run: echo "$COMMITS"
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"
      - name: skipping step if message has '#skip'
        if: ${{ SHOULD_SKIP_TAG_RELEASE }}
        run: echo "this shouldn't be printed if commit's message has '#skip' inside."

